import math
DEBUG = 1
PARKING_NODE_COLOR = '#FF0099'
EXIT_NODE_COLOR = 'r'
STREET_NODE_COLOR = 'g'

#Simulation parameter
UNIT_LENGTH = math.ceil(5000/738)   #ft
AVERAGE_CAR_SPACE_LENGTH = 20 #ft
AVERAGE_CAR_SPEED = 37 #ft/s