import math
DEBUG = 1
PARKING_NODE_COLOR = '#FF0099'
EXIT_NODE_COLOR = 'r'
STREET_NODE_COLOR = 'g'
COP_NODE_COLOR = 'b'
COP_MODE = 1
COP_INTERSECTION_THRESHOLD = 4
COP_CONGESTION_THRESHOLD = 0.5
DEPTH_OF_AWARENESS = 1
EAST_TENDENCY = 0.2
SPACE_TIME_TRADEOFF = 1
DEAD_END = []
#Simulation parameter
UNIT_LENGTH = math.ceil(5000/738)   #ft
AVERAGE_CAR_SPACE_LENGTH = 20 #ft
AVERAGE_CAR_SPEED = 37 #ft/s